# @code-as-a-doc: file | param: "${*}"
apiVersion: provisioning.dpu.hcp.io/v1alpha1
kind: DPFHCPProvisioner
metadata:
  name: ${HOSTED_CLUSTER_NAME}
  namespace: ${CLUSTERS_NAMESPACE}
spec:
  baseDomain: ${BASE_DOMAIN}
  dpuClusterRef:
    name: ${HOSTED_CLUSTER_NAME}
    namespace: dpf-operator-system
  dpuDeploymentRef:
    name: dpudeployment
    namespace: dpf-operator-system
  etcdStorageClass: ${ETCD_STORAGE_CLASS}
  ocpReleaseImage: ${OCP_RELEASE_IMAGE}
  pullSecretRef:
    name: ${PULL_SECRET_NAME}
  sshKeySecretRef:
    name: ${SSH_KEY_SECRET_NAME}
  virtualIP: ${HOSTED_CLUSTER_VIP}
