# @code-as-a-doc: file | param: "${*}"
apiVersion: v1
kind: Secret
metadata:
  name: ${WORKER_NAME}-bmc-secret
  namespace: openshift-machine-api
type: Opaque
stringData:
  username: ${BMC_USER}
  password: ${BMC_PASSWORD}
