apiVersion: noderesources.dpu.nvidia.com/v1alpha1
kind: NodeSRIOVDevicePluginConfig
metadata:
  name: bf3-vfs
  namespace: dpf-operator-system
spec:
  devicePluginResources:
    - name: bf3-p0-vfs-mgmt # Reserves VF index 1 on PF0 for DPU management connectivity
      type: vf
      ranges:
        - pfIndex: 0
          start: 1
          end: 1
    - name: bf3_vfs # Allocates VF 2-45 on PF0 and VF 0-45 on PF1 for workload traffic with RDMA enabled
      type: vf
      options:
        isRdma: true
      ranges:
        - pfIndex: 0 # first physical function of the BlueField-3 DPU
          start: 2
          end: 45
        - pfIndex: 1 # second physical function of the BlueField-3 DPU
          start: 0
          end: 45
